### ISSUE TITLE
Investigate why the /branch Jenkins build always fails

### ISSUE THREAD

**Issue by keithm-xmos** [xmos/xcore_sdk#476]

**Comment by keithm-xmos** [comment]
This may be because Jenkins expects a build on the "compare" branch of a PR.  To test this theory, try changing the triggers in `ci.yml`

```
name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'
      - 'develop'
```
